### ISSUE TITLE
Import Error (from mcapi import *)

### ISSUE THREAD

**Issue by Roxiun** [Macuyiko/minecraft-python#38]
When running `from mcapi import *` I get the error:

```
from org.bukkit import Location, Color, Effect, Material, Sound, TreeType, Particle, FireworkEffect
ImportError: cannot import name Particle
```

(Running Latest python.jar release on `spigot 1.8.8`)

**Comment by Macuyiko** [comment]
That's probably because Spigot 1.8.8 did not have Particle types yet. You can try to modify mcapi to remove `Particle`, `FireworkEffect` and the methods using that. (Or see an earlier version in the commit history https://github.com/Macuyiko/minecraft-python/commits/master/ServerPythonInterpreterPlugin/python/mcapi.py

**Comment by spookybear0** [comment]
Maybe there could be a version check?

**Comment by Macuyiko** [comment]
Yep, that's not too bad of an idea. I'd be welcome to PR for that. Preferably, `mcapi.py` should import the actual file it needs depending on the detected version.

Alternatively, users on older versions of Spigot should be able to make a `mcapi-local.py` copy and modify it accordingly.
