### ISSUE TITLE
ImportError: cannot import name Particle

### ISSUE THREAD

**Issue by LMS5413** [Macuyiko/minecraft-python#52]
When I put the following code 

```python
from mcapi import *


explosion(lookingat(player("LM5413")), power=2)
```

gives this error.
![imagem_2021-09-28_124612](https://user-images.githubusercontent.com/58144443/135120986-c3504386-8f69-40a5-a02f-8f9416e4b075.png)

**Comment by Macuyiko** [comment]
Not able to replicate this using Spigot 1.17.1. Which server are you using?

**Comment by LMS5413** [comment]
> Not able to replicate this using Spigot 1.17.1. Which server are you using?

1.8.8

**Comment by Macuyiko** [comment]
Particles were probably not in 1.8.8 yet? mcapi.py tries to be compatible with the current releases. If you're working with an older Spigot version, I'd suggest to uncomment the Particle (and perhaps other) import.

It might be a good idea to make this a bit more smarter/flexible in the future instead of hard failing, tho.
