### ISSUE TITLE
Question: Use this plugin to create new plugins written in python?

### ISSUE THREAD

**Issue by arve0** [Macuyiko/minecraft-python#6]
Hi!
I'm a volunteer in kodeklubben (a Norwegian code club), where we teach kids to code. We have a lot of kids interested in developing plugins for minecraft. Currently, we have courses in scratch, python, java and minecraft. The minecraft course is based on [Learn to Program with Minecraft Plugins](https://pragprog.com/book/ahmine2/learn-to-program-with-minecraft-plugins), but due to licensing issues we are not allowed to create new lessons based on code from Andy Hunt's book.

Also, the kids are quite young and they waste a lot of time on issues like syntax, environment setup, etc. As most of them learn python first, it might be easier for them if they hadn't needed to learn another syntax before creating simple plugins.

I haven't read your code and I'm not very familiar with minecraft or canarymod, so I though to cut some corners by asking. Do you think it's feasible to develop plugins with python for redistribution (they love to share with friends)? And if so, what do you think would be a good approach/place to start? I guess one would need to package the plugin after it has been written, as I understand MinecraftPythonConsole is more of an interactive kind of thingy?

**Comment by Macuyiko** [comment]
Hi there! Thanks for your interest!

To answer your questions in an as-quick-as-possible manner:
- "Learning Python first, not wasting time with Java": This is a good fit. Everything is done from Python (Jython). Sometimes you need to work around some quirks in the Python -> Java translation, but it's possible to wrap some methods around this, which you can offer as easy access points to your pupils. I.e. that's what this: https://github.com/Macuyiko/MinecraftPythonConsole/blob/master/ServerPythonInterpreterPlugin/python/mcapi.py is for
- "Do you think it's feasible to develop plugins with python for redistribution?": Yes. Either in two ways: 1) you provide the server and kids run their code there (others can see the results reflected immediately) or 2) kids share/distribute Python source files.
- "I guess one would need to package the plugin after it has been written, as I understand MinecraftPythonConsole is more of an interactive kind of thingy?": That's correct. Interpreter shells are accessible over Telnet, Websockets, or the web. However, packaging plugins is not that infeasible. Currently, the plugin makes sure that the "/python" folder is added to the system path in order to make it easy to import code from that location. Similarly, it'd be possible to change the plugin to also look in a folder ("/python-plugins", for instance), and auto-load all .py files it finds there. Since it is possible to define command and event hooks from Python code (see latest/upcoming commits for that), this thus allows to create fully stand-alone plugins and share them. To run them locally, you'd need to: install Canary, download my mod, download a Python mod from another kid, start server, connect, and off you go.

That's it in a nutshell. If any of this seem interesting, feel free to follow up (here or by email: macuyiko at gmail dot com).

**Comment by arve0** [comment]
Thanks! I'll keep you updated when we do any work on this. :octocat:

**Comment by pauleveritt** [comment]
Hi Seppe. I'm interested in working on this repo with my son during my summer break. I wonder if you still have any plans for it, and if you're open to any contributors.

**Comment by pauleveritt** [comment]
Oops, I should have added, I'm also interested in contributing on some of the aspects that @arve0 mentioned.
