### ISSUE TITLE
Dynamic command registration doesn't work for 1.19.2 servers

### ISSUE THREAD

**Issue by bjcosta** [Macuyiko/minecraft-python#61]
This plugin is a fantastic idea giving full access with minimal work! Thanks for developing this. I am surprised more people are not using it. 

I am planning to teach my kids some python coding and this seems like the perfect way to do so (if I write some simple wrappers for them to use).

When I add this plugin to my paper server I am expecting to see "Hello world" on the console when I type:

_/testcommand_

The following works fine for a 1.18.2 paper server but not for a 1.19.2 paper server in which case I see no output.
```
import mcapi
def TestCommand(sender, parameters):
    sender.sendMessage('Hello world')
    return True

mcapi.add_command('testcommand', TestCommand)
```

I did some debugging of this and I could see the command is registered as expected and force a dispatch of the command manually myself in 1.192.2 manually using something like:

`CommandMap.dispatch(player, 'ctest')
`

However typing it in the console of the game has no effect.

I was wondering, does this plugin need to be rebuilt every server version we want to run it on to ensure it works correctly and could this be the cause of the bug or maybe 1.19.2 dispatches commands in a very different way (the canonical way is editing plugin.yml but wanting python scripts as individual plugins I dont have that luxury)?

If it is likely because the plugin needs to be rebuilt for a new version, could you please provide some instructions in the readme on the main page on how best to do this?

(I saw past commit for 1.18.2 which was mixed with other changes). Should I just replace the spigot-api-1.18.2-R0.1-20220513.012838-41-shaded.jar with a more recent server jar and then rebuild using makejar.bat?

If this is not the issue, do you have any hints where I can look to resolve this issue?

Thanks again.

**Comment by Macuyiko** [comment]
Thanks for reporting this. This seems to be due to client changes in 1.19.2. The newest release implements a custom listener which just calls .dispatch() itself when a command matches one registered in the command map. Note that Minecraft will still complain about the command not existing whilst typing the command, but will correctly execute it. (The latter issue might be fixed by using a custom TabCompleter listener, but also that seems to have changed and does not fire anymore until arguments are added.)
